// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/landing-vibes/CorporateClarity.tsx": () => import("../components/mockups/landing-vibes/CorporateClarity.tsx"),
  "./components/mockups/landing-vibes/DarkTechnical.tsx": () => import("../components/mockups/landing-vibes/DarkTechnical.tsx"),
  "./components/mockups/landing-vibes/WarmHuman.tsx": () => import("../components/mockups/landing-vibes/WarmHuman.tsx")
};
